<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class TableCurrency extends Seeder
{
    /**
     * 币种信息初始化
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \DB::table('currency')->delete();

        \DB::table('currency')->insert(array(
            array(
                'id'                     => '1',
                'name'                   => 'BTC',
                'trading_pair_id'        => '1',
                'k_line_code'            => 'btcusdt',
                'decimal_scale'          => '8',
                'type'                   => '2,3',
                'sort'                   => '0',
                'is_hidden'              => '1',
                'fluctuation_min'        => '0.00001',
                'fluctuation_max'        => '0.00010',
                'fee_currency_currency'  => '0.02',
                'fee_perpetual_contract' => '0.05',
                'fee_option_contract'    => '0.05',
            ),
            array(
                'id'                     => '2',
                'name'                   => 'ETC',
                'trading_pair_id'        => '1',
                'k_line_code'            => 'etcusdt',
                'decimal_scale'          => '8',
                'type'                   => '2,3',
                'sort'                   => '0',
                'is_hidden'              => '1',
                'fluctuation_min'        => '0.00001',
                'fluctuation_max'        => '0.00010',
                'fee_currency_currency'  => '0.02',
                'fee_perpetual_contract' => '0.05',
                'fee_option_contract'    => '0.05',
            ),
            array(
                'id'                     => '3',
                'name'                   => 'XRP',
                'trading_pair_id'        => '1',
                'k_line_code'            => 'xrpusdt',
                'decimal_scale'          => '8',
                'type'                   => '2',
                'sort'                   => '0',
                'is_hidden'              => '1',
                'fluctuation_min'        => '0.00001',
                'fluctuation_max'        => '0.00010',
                'fee_currency_currency'  => '0.02',
                'fee_perpetual_contract' => '0.05',
                'fee_option_contract'    => '0.05',
            ),
            array(
                'id'                     => '4',
                'name'                   => 'ADA',
                'trading_pair_id'        => '1',
                'k_line_code'            => 'adausdt',
                'decimal_scale'          => '8',
                'type'                   => '2',
                'sort'                   => '0',
                'is_hidden'              => '1',
                'fluctuation_min'        => '0.00001',
                'fluctuation_max'        => '0.00010',
                'fee_currency_currency'  => '0.02',
                'fee_perpetual_contract' => '0.05',
                'fee_option_contract'    => '0.05',
            ),
            array(
                'id'                     => '5',
                'name'                   => 'LTC',
                'trading_pair_id'        => '1',
                'k_line_code'            => 'ltcusdt',
                'decimal_scale'          => '8',
                'type'                   => '2',
                'sort'                   => '0',
                'is_hidden'              => '1',
                'fluctuation_min'        => '0.00001',
                'fluctuation_max'        => '0.00010',
                'fee_currency_currency'  => '0.02',
                'fee_perpetual_contract' => '0.05',
                'fee_option_contract'    => '0.05',
            ),
            array(
                'id'                     => '6',
                'name'                   => 'XEM',
                'trading_pair_id'        => '1',
                'k_line_code'            => 'xemusdt',
                'decimal_scale'          => '8',
                'type'                   => '2',
                'sort'                   => '0',
                'is_hidden'              => '1',
                'fluctuation_min'        => '0.00001',
                'fluctuation_max'        => '0.00010',
                'fee_currency_currency'  => '0.02',
                'fee_perpetual_contract' => '0.05',
                'fee_option_contract'    => '0.05',
            ),
            array(
                'id'                     => '7',
                'name'                   => 'DASH',
                'trading_pair_id'        => '1',
                'k_line_code'            => 'dashusdt',
                'decimal_scale'          => '8',
                'type'                   => '2',
                'sort'                   => '0',
                'is_hidden'              => '1',
                'fluctuation_min'        => '0.00001',
                'fluctuation_max'        => '0.00010',
                'fee_currency_currency'  => '0.02',
                'fee_perpetual_contract' => '0.05',
                'fee_option_contract'    => '0.05',
            ),
            array(
                'id'                     => '8',
                'name'                   => 'XLM',
                'trading_pair_id'        => '1',
                'k_line_code'            => 'xlmusdt',
                'decimal_scale'          => '8',
                'type'                   => '2',
                'sort'                   => '0',
                'is_hidden'              => '1',
                'fluctuation_min'        => '0.00001',
                'fluctuation_max'        => '0.00010',
                'fee_currency_currency'  => '0.02',
                'fee_perpetual_contract' => '0.05',
                'fee_option_contract'    => '0.05',
            ),
            array(
                'id'                     => '9',
                'name'                   => 'ETH',
                'trading_pair_id'        => '2',
                'k_line_code'            => 'ethbtc',
                'decimal_scale'          => '8',
                'type'                   => '2',
                'sort'                   => '0',
                'is_hidden'              => '1',
                'fluctuation_min'        => '0.00001',
                'fluctuation_max'        => '0.00010',
                'fee_currency_currency'  => '0.02',
                'fee_perpetual_contract' => '0.05',
                'fee_option_contract'    => '0.05',
            ),
            array(
                'id'                     => '10',
                'name'                   => 'XRP',
                'trading_pair_id'        => '2',
                'k_line_code'            => 'xrpbtc',
                'decimal_scale'          => '8',
                'type'                   => '2',
                'sort'                   => '0',
                'is_hidden'              => '1',
                'fluctuation_min'        => '0.00001',
                'fluctuation_max'        => '0.00010',
                'fee_currency_currency'  => '0.02',
                'fee_perpetual_contract' => '0.05',
                'fee_option_contract'    => '0.05',
            ),
            array(
                'id'                     => '11',
                'name'                   => 'EOS',
                'trading_pair_id'        => '2',
                'k_line_code'            => 'eosbtc',
                'decimal_scale'          => '8',
                'type'                   => '2',
                'sort'                   => '0',
                'is_hidden'              => '1',
                'fluctuation_min'        => '0.00001',
                'fluctuation_max'        => '0.00010',
                'fee_currency_currency'  => '0.02',
                'fee_perpetual_contract' => '0.05',
                'fee_option_contract'    => '0.05',
            ),
            array(
                'id'                     => '12',
                'name'                   => 'DOT',
                'trading_pair_id'        => '2',
                'k_line_code'            => 'dotbtc',
                'decimal_scale'          => '8',
                'type'                   => '2',
                'sort'                   => '0',
                'is_hidden'              => '1',
                'fluctuation_min'        => '0.00001',
                'fluctuation_max'        => '0.00010',
                'fee_currency_currency'  => '0.02',
                'fee_perpetual_contract' => '0.05',
                'fee_option_contract'    => '0.05',
            ),
            array(
                'id'                     => '13',
                'name'                   => 'EOS',
                'trading_pair_id'        => '3',
                'k_line_code'            => 'eoseth',
                'decimal_scale'          => '8',
                'type'                   => '2',
                'sort'                   => '0',
                'is_hidden'              => '1',
                'fluctuation_min'        => '0.00001',
                'fluctuation_max'        => '0.00010',
                'fee_currency_currency'  => '0.02',
                'fee_perpetual_contract' => '0.05',
                'fee_option_contract'    => '0.05',
            ),
            array(
                'id'                     => '14',
                'name'                   => 'LINK',
                'trading_pair_id'        => '3',
                'k_line_code'            => 'linketh',
                'decimal_scale'          => '8',
                'type'                   => '2',
                'sort'                   => '0',
                'is_hidden'              => '1',
                'fluctuation_min'        => '0.00001',
                'fluctuation_max'        => '0.00010',
                'fee_currency_currency'  => '0.02',
                'fee_perpetual_contract' => '0.05',
                'fee_option_contract'    => '0.05',
            ),
            array(
                'id'                     => '15',
                'name'                   => 'ADA',
                'trading_pair_id'        => '3',
                'k_line_code'            => 'adaeth',
                'decimal_scale'          => '8',
                'type'                   => '2',
                'sort'                   => '0',
                'is_hidden'              => '1',
                'fluctuation_min'        => '0.00001',
                'fluctuation_max'        => '0.00010',
                'fee_currency_currency'  => '0.02',
                'fee_perpetual_contract' => '0.05',
                'fee_option_contract'    => '0.05',
            ),
            array(
                'id'                     => '16',
                'name'                   => 'XMR',
                'trading_pair_id'        => '3',
                'k_line_code'            => 'xmreth',
                'decimal_scale'          => '8',
                'type'                   => '2',
                'sort'                   => '0',
                'is_hidden'              => '1',
                'fluctuation_min'        => '0.00001',
                'fluctuation_max'        => '0.00010',
                'fee_currency_currency'  => '0.02',
                'fee_perpetual_contract' => '0.05',
                'fee_option_contract'    => '0.05',
            ),

        ));
    }
}
